module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: digest 0.0.1.2

  Hackage: zip-archive 0.2'
ghc-args: []
excluded-modules: []
